### ISSUE TITLE
The recommended `static` URL is not optimal

### ISSUE THREAD

**Issue by OmarIthawi** [ahmedaljazzar/django-mako#1]
Thank you @ahmedaljazzar for creating the library!

In the `README.md` file this library recommends the following:

> 3. To include a static file url:
> ${ static }/home.png

Which has been added with in [`djangomako/backends.py`](https://github.com/ahmedaljazzar/django-mako/blob/1834e8dfb7a88e134e588f48c972ec513fa6fa21/djangomako/backends.py#L159):

    context['static'] = staticfiles_storage.url

I think this variable should not be used directly. Instead we should use the `static` helper instead. Quoting a [StackOverflow answer](https://stackoverflow.com/a/19369666/161278):

> Since this is the top result on Google, I thought I'd add another way to do this. Personally I prefer this one, since it leaves the implementation to the Django framework.
> 
>     from django.contrib.staticfiles.templatetags.staticfiles import static
> 
>     url = static('x.jpg')
>     # url now contains '/static/x.jpg', assuming a static path of '/static/'

I'm recommending this approach since it will correctly renames `x.png` to `x.f0de3f9.png` when needed for cache busting.

Let me know if I should clarify more!

**Comment by iamjazzar** [comment]
No need @OmarIthawi, and thanks for your suggestion. Please find your comment addressed in #2.
If you have any other comments please feel free to write them. 😄

**Comment by OmarIthawi** [comment]
Awesome 😃

**Comment by iamjazzar** [comment]
Solved in #2
