### ISSUE TITLE
djangomako pypi showing latest package version as 1.3.0 when 1.3.1 is released

### ISSUE THREAD

**Issue by Harshg999** [ahmedaljazzar/django-mako#15]
Hey @iamjazzar, `djangomako==1.3.1` fixes a high severity Mako CVE by supporting 1.2.2 but it is not available on pypi yet. Can this be released on pypi too? Thanks!

**Comment by iamjazzar** [comment]
New release published to PyPi. Thanks for flagging this, something went wrong in the CD system it's fixed now.
